### ISSUE TITLE
powstream frequent errors (Invalid transition or No such file)

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#199]
Reported earlier to the mailing list.

In my host (fresh Netinstall + latest yum update, IP not added to DNS, no firewall, no pscheduler limits) I configured two types of tests:
- to bwctl host
- to psc host (perfsonardev2.internet2.edu)
  I see a lot of powstream frequent errors (also visible as plenty of red dots in graphs for both bwctl and psc tests). In general tests seems to be running (there are values in the graphs):

```
# tail -f messages
Oct 21 14:12:26 localhost journal: merged-results INFO     Started
Oct 21 14:12:26 localhost journal: merged-results INFO     Started
Oct 21 14:12:26 localhost journal: participant-data INFO     Started
Oct 21 14:12:26 localhost journal: participant-data INFO     Started
Oct 21 14:12:27 localhost journal: participant-data INFO     Started
Oct 21 14:12:27 localhost journal: participant-data INFO     Started
Oct 21 14:12:28 localhost journal: participant-data INFO     Started
Oct 21 14:12:28 localhost journal: participant-data INFO     Started
Oct 21 14:12:30 localhost journal: participant-data INFO     Started
Oct 21 14:12:30 localhost journal: participant-data INFO     Started
Oct 21 14:12:31 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[9873                                                                   ]: open(/var/lib/pscheduler/tool/powstream/7aad655d-79fc-4663-89e5-571bd9d86665/15831423926345474698_15831424187276570379.owp.i)                                                                   : No such file or directory
Oct 21 14:12:31 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[9873                                                                   ]: open(/var/lib/pscheduler/tool/powstream/7aad655d-79fc-4663-89e5-571bd9d86665/15831423926345474698_15831424187276570379.owp.i)                                                                   : No such file or directory
Oct 21 14:12:31 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[9873                                                                   ]: open(/var/lib/pscheduler/tool/powstream/7aad655d-79fc-4663-89e5-571bd9d86665/15831423926345474698_15831424187276570379.owp.i)                                                                   : No such file or directory
Oct 21 14:12:31 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[9873                                                                   ]: open(/var/lib/pscheduler/tool/powstream/7aad655d-79fc-4663-89e5-571bd9d86665/15831423926345474698_15831424187276570379.owp.i)                                                                   : No such file or directory
Oct 21 14:12:31 localhost journal: participant-data INFO     Started
Oct 21 14:12:31 localhost journal: participant-data INFO     Started
Oct 21 14:12:31 localhost journal: archiver-esmond/archive INFO     Started
Oct 21 14:12:31 localhost journal: archiver-esmond/archive INFO     Started
Oct 21 14:12:31 localhost journal: archiver-esmond/archive INFO     Started
Oct 21 14:12:31 localhost journal: archiver-esmond/archive INFO     Started
Oct 21 14:12:31 localhost journal: archiver-esmond/archive INFO     Started
Oct 21 14:12:31 localhost journal: archiver-esmond/archive INFO     Started
Oct 21 14:12:32 localhost journal: participant-data INFO     Started
Oct 21 14:12:32 localhost journal: participant-data INFO     Started
Oct 21 14:12:33 localhost journal: runner ERROR    28358: Got NULL part_data_full
Oct 21 14:12:33 localhost journal: runner ERROR    28358: Got NULL part_data_full
Oct 21 14:12:33 localhost journal: tool-powstream/run INFO     Started
Oct 21 14:12:33 localhost journal: tool-powstream/run INFO     Started
Oct 21 14:12:33 localhost journal: tool-powstream/run INFO     Started
Oct 21 14:12:33 localhost journal: tool-powstream/run INFO     Started
Oct 21 14:12:33 localhost journal: tool-powstream/run INFO     Started
Oct 21 14:12:33 localhost journal: tool-powstream/run INFO     Started
Oct 21 14:12:34 localhost journal: participant-data INFO     Started
Oct 21 14:12:34 localhost journal: participant-data INFO     Started
Oct 21 14:12:35 localhost journal: participant-data INFO     Started
Oct 21 14:12:35 localhost journal: participant-data INFO     Started
Oct 21 14:12:36 localhost journal: runner ERROR    Exception: InternalError: Invalid transition between states (5 to 8).#012#012                                                                   Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012                                                                     File "/usr/libexec/pscheduler/daemons/runner", line 366, in __run#012    self.id])#012InternalError: Invalid transition between                                                                    states (5 to 8).
Oct 21 14:12:36 localhost journal: runner ERROR    Exception: InternalError: Invalid transition between states (5 to 8).#012#012                                                                   Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012                                                                     File "/usr/libexec/pscheduler/daemons/runner", line 366, in __run#012    self.id])#012InternalError: Invalid transition between                                                                    states (5 to 8).
Oct 21 14:12:37 localhost journal: participant-data INFO     Started
Oct 21 14:12:37 localhost journal: participant-data INFO     Started
Oct 21 14:12:38 localhost journal: participant-data INFO     Started
Oct 21 14:12:38 localhost journal: participant-data INFO     Started

```

I may provide the whole log upon request.

**Comment by szymontrocha** [comment]
Attaching psc diags results
[psc_diags.txt](https://github.com/perfsonar/pscheduler/files/544287/psc_diags.txt)

**Comment by mfeit-internet2** [comment]
The transition problem may have been resolved by d159c54ba46ec3d33ec3f579e76adc5447de7fb2.  Close this if you don't continue seeing this problem after RC2.

**Comment by mfeit-internet2** [comment]
Found and fixed at least one thing that may be contributing to this.

**Comment by szymontrocha** [comment]
I think things didn't change much:
Nov  4 09:55:23 localhost journal: safe_run/runner ERROR    Program threw an exception after 0:00:36.051036
Nov  4 09:55:23 localhost journal: safe_run/runner ERROR    Program threw an exception after 0:00:36.051036
Nov  4 09:55:23 localhost journal: safe_run/runner ERROR    Exception: InternalError: Invalid transition between states (5 to 2).#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/runner", line 619, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/runner", line 576, in main_program#012    """, (tuple(run_ids),))#012InternalError: Invalid transition between states (5 to 2).
Nov  4 09:55:23 localhost journal: safe_run/runner ERROR    Exception: InternalError: Invalid transition between states (5 to 2).#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/runner", line 619, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/runner", line 576, in main_program#012    """, (tuple(run_ids),))#012InternalError: Invalid transition between states (5 to 2).
Nov  4 09:55:23 localhost journal: safe_run/runner ERROR    Waiting 24.25 seconds before restarting
Nov  4 09:55:23 localhost journal: safe_run/runner ERROR    Waiting 24.25 seconds before restarting
Nov  4 09:55:24 localhost journal: runner ERROR    Exception: InternalError: Invalid transition between states (5 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (5 to 3).
Nov  4 09:55:24 localhost journal: runner ERROR    Exception: InternalError: Invalid transition between states (5 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (5 to 3).

**Comment by mfeit-internet2** [comment]
Discussed in Slack, but repeated here:  The changed code hasn't been pushed out yet.

**Comment by szymontrocha** [comment]
Errors are still there after today's yum update, although less frequent I think:
Nov 10 16:01:12 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:12 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:12 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:14 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:14 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:14 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:14 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:14 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:01:14 localhost journal: archiver-esmond/archive INFO     Started
Nov 10 16:02:14 localhost journal: runner ERROR    230360: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:02:14 localhost journal: runner ERROR    230360: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:03:14 localhost journal: runner ERROR    230364: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:03:14 localhost journal: runner ERROR    230364: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:03:24 localhost journal: runner ERROR    230366: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:03:24 localhost journal: runner ERROR    230366: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:04:24 localhost journal: runner ERROR    230370: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:04:24 localhost journal: runner ERROR    230370: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:04:24 localhost journal: runner ERROR    230369: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:04:24 localhost journal: runner ERROR    230369: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:04:28 localhost journal: runner ERROR    230371: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:04:28 localhost journal: runner ERROR    230371: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:05:28 localhost journal: runner ERROR    230375: Failed to set running state: Invalid transition between states (5 to 3).
Nov 10 16:05:28 localhost journal: runner ERROR    230375: Failed to set running state: Invalid transition between states (5 to 3).

**Comment by mfeit-internet2** [comment]
This should be gone now that the database has been optimized.
